spring.application.name=backend
spring.config.import=classpath:aplication-secrets.properties

spring.messages.basename = messages


spring.datasource.url=jdbc:mysql://localhost:5244/financeiro
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Criação da Tabela
spring.jpa.hibernate.ddl-auto=update

#configuração email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=frankwco@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true